site_name: DS Lambda notes
theme:
  name: material
  theme_dir: 'mkdocs-material/material'
  custom_dir: theme
  features:
    - instant

nav:
  - Home: index.md

  - Sprint 1:
      - Assignments:
        - 111 Exploratory Data Analysis: ./sprint-1/Assignments/LS_DS_111_Exploratory_Data_Analysis_Assignment.ipynb
        - 112 Make Features: ./sprint-1/Assignments/LS_DS_112_Make_Features_Assignment.ipynb
        - 113 Join and Reshape Data: ./sprint-1/Assignments/LS_DS_113_Join_and_Reshape_Data_Assignment.ipynb
        - 114 Make Explanatory Visualizations: ./sprint-1/Assignments/LS_DS_114_Make_Explanatory_Visualizations_Assignment.ipynb
      - Lecture:
        - ./sprint-1/Lecture/LS_DS16_111_Exploratory_Data_Analysis.ipynb
        - ./sprint-1/Lecture/LS_DS16_112_Make_Features.ipynb
        - ./sprint-1/Lecture/LS_DS16_113_Join_and_Reshape_Data.ipynb
        - ./sprint-1/Lecture/LS_DS16_114_Make_Explanatory_Visualizations.ipynb
  - Sprint 2:
      - Assignments:
          - ./sprint-2/Assignments/LS_DS_121_Statistics_Probability_Assignment.ipynb
          - ./sprint-2/Assignments/LS_DS_122_Sampling_Confidence_Intervals_and_Hypothesis_Testing_Assignment.ipynb
          - ./sprint-2/Assignments/LS_DS_123_Introduction_to_Bayesian_Inference_Assignment.ipynb
          - Module 4: ./sprint-2/Assignments/template.md
      - Lecture:
          - ./sprint-2/Lecture/LS_DS16_121_Statistics_Probability_and_Inference.ipynb
          - ./sprint-2/Lecture/LS_DS16_122_Sampling_Confidence_Intervals_and_Hypothesis_Testing.ipynb
          - ./sprint-2/Lecture/LS_DS16_123_Introduction_to_Bayesian_Inference.ipynb
      - Q & A:
          - ./sprint-2/Q-and-A/Statistics_Wednesday_Q&A_DS16.ipynb
          - ./sprint-2/Q-and-A/Thursday_Statistics_Q&A_DS16.ipynb
  - Sprint 3:
      - Assignments:
          - ./sprint-3/assignments/LS_DS_131_Vectors_and_Matrices_Assignment.ipynb
          - ./sprint-3/assignments/LS_DS_132_Intermediate_Linear_Algebra_Assignment.ipynb
          - ./sprint-3/assignments/LS_DS_133_High_Dimensional_Data_Assignment.ipynb
          - ./sprint-3/assignments/LS_DS_134_Clustering_Assignment.ipynb
      - Lecture:
          - ./sprint-3/lecture/LS_DS_131_Vectors_and_Matrices.ipynb
          - ./sprint-3/lecture/LS_DS_132_Intermediate_Linear_Algebra.ipynb
          - ./sprint-3/lecture/LS_DS_133_High_Dimensional_Data.ipynb
          - ./sprint-3/lecture/LS_DS_134_Clustering_and_NFL.ipynb

plugins:
  - localsearch
  - mkdocs-jupyter


extra_javascript:
    - search/search_index.js